export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_CATEGORY_POSTS = 'LOAD_CATEGORY_POSTS';
export const LOAD_SINGLE_POST = 'LOAD_SINGLE_POST';

export const LOAD_POST_COMMENTS = 'LOAD_POST_COMMENTS';
export const LOAD_SINGLE_COMMENT = 'LOAD_SINGLE_COMMENT';

export const VOTE_POST_SUCCESSFUL = 'VOTE_POST_SUCCESSFUL';
export const VOTE_COMMENT_SUCCESSFUL = 'VOTE_COMMENT_SUCCESSFUL';
