export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_CATEGORY_POSTS = 'LOAD_CATEGORY_POSTS';
export const LOAD_SINGLE_POST = 'LOAD_SINGLE_POST';

export const LOAD_POST_COMMENTS = 'LOAD_POST_COMMENTS';